Repository Open-Science-Community-Saudi-Arabia/JSquarto, pull requests merged in 2024-04, with the labels that each got.

#36 [05/04/2024] Add changelog to tutorials in generated doc
  tutorials/changelog.qmd
Labels: kind/documentation, size/M

#39 List English only once
  docs/_quarto.yml
Labels: size/XS, kind/documentation

#42 [22-04-2024]: Update tutorial on using CLI arguments
  tutorials/how_to/optimizing_workflow.qmd
Labels: kind/documentation, size/M

#43 [22-04-2024]: Exclude main languge from other languages config
  src/utils/writer.ts
Labels: kind/bug, size/XS

#46 [29/04/2024] fix: duplicate languages in dropdown menu for switching languages
  README.md
  docs/_quarto.yml
  package-lock.json
  package.json
  src/fixes/fix_duplicate_language_refs.ts
  src/fixes/fix_localized_index_file.ts
  src/index.ts
  src/utils/htmlparser.ts
  tutorials/how_to/optimizing_workflow.qmd
Labels: kind/bug, size/L
